// <auto-generated />
using System;
using Banking.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Banking.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241026124258_Banking")]
    partial class Banking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Banking.Domain.Entities.PaymentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentDirection")
                        .HasColumnType("integer");

                    b.Property<Guid>("PaymentSystemId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PaymentSystemId");

                    b.ToTable("PaymentRequests");
                });

            modelBuilder.Entity("Banking.Domain.Entities.PaymentSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTest")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaximumLimit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinimumLimit")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentDirection")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PaymentSystems");
                });

            modelBuilder.Entity("Banking.Domain.Entities.PaymentRequest", b =>
                {
                    b.HasOne("Banking.Domain.Entities.PaymentSystem", "PaymentSystem")
                        .WithMany()
                        .HasForeignKey("PaymentSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentSystem");
                });
#pragma warning restore 612, 618
        }
    }
}
