version: '3.8'

services:

   rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
   
   rabbitmqinitializer:
    build:
     context: .
     dockerfile: RabbitMQ/RabbitMqInitializer/Dockerfile
    container_name: rabbitmqinitializer
    restart: on-failure
    
   # seq:
   #  image: datalust/seq:latest
   #  container_name: seq
   #  hostname: seq
   #  environment:
   #    - ACCEPT_EULA=Y
   #  ports:
   #    - 5341:80

   banking:
    build:
      context: .
      dockerfile: Banking/Banking.Api/Dockerfile
    container_name: banking
    restart: on-failure
    ports:
      - "5003:8080"
      - "5004:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - POSTGRES_CONNECTION_STRING=Host=${HOST};Port=${POSTGRE_DB_PORT};Database=${BANKING_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - USERS_GRPC_SERVICE_URL=https://${HOST}${USERS_GRPC_SERVICE_PORT}
    volumes:
      - ./certs:/https-certs:ro 

   gateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    container_name: gateway
    restart: on-failure
    ports:
      - "5100:8080"
      - "5101:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./certs:/https-certs:ro 
